vich_uploader:
  db_driver: orm
  mappings:
    user_profile_images:
      uri_prefix: '%app.path.user_profile_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.user_profile_images%'